// SPDX-FileCopyrightText: 2025 ArtisticRoomba <145879011+ArtisticRoomba@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 qrwas <aleksandr.vernigora93@gmail.com>
// SPDX-FileCopyrightText: 2026 Ilya Mikheev <me@ilyamikcoder.com>
//
// SPDX-License-Identifier: MIT

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Lobby.UI.Loadouts;

/// <summary>
/// A button that toggles the loadout groups. Needs for override default styles.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ToggleLoadoutButton : Button;
