// SPDX-FileCopyrightText: 2023 Ed <96445749+TheShuEd@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 LordCarve <27449516+LordCarve@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 imatsoup <93290208+imatsoup@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 Ilya Mikheev <me@ilyamikcoder.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Shared.Thief;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Thief;

[GenerateTypedNameReferences]
public sealed partial class ThiefBackpackMenu : FancyWindow
{
    [Dependency] private readonly IEntitySystemManager _sysMan = default!;
    private readonly SpriteSystem _spriteSystem;

    public event Action? OnApprove;
    public event Action<int>? OnSetChange;

    public ThiefBackpackMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _sysMan.GetEntitySystem<SpriteSystem>();

        ApproveButton.OnPressed += args =>
        {
            OnApprove?.Invoke();
        };
    }

    public void UpdateState(ThiefBackpackBoundUserInterfaceState state)
    {
        SetsGrid.RemoveAllChildren();
        var selectedNumber = 0;
        foreach (var (set, info) in state.Sets)
        {
            var child = new ThiefBackpackSet(info, _spriteSystem);

            child.SetButton.OnButtonDown += (args) =>
            {
                OnSetChange?.Invoke(set);
            };

            SetsGrid.AddChild(child);

            if (info.Selected)
                selectedNumber++;
        }

        Title = Loc.GetString(state.ToolName);
        Description.Text = Loc.GetString(state.ToolDesc, ("maxCount", state.MaxSelectedSets));
        SelectedSets.Text = Loc.GetString("thief-backpack-window-selected", ("selectedCount", selectedNumber), ("maxCount", state.MaxSelectedSets));
        ApproveButton.Disabled = selectedNumber != state.MaxSelectedSets;
    }
}
