# SPDX-FileCopyrightText: 2025 poklj <compgeek223@gmail.com>
# SPDX-FileCopyrightText: 2026 Ilya Mikheev <me@ilyamikcoder.com>
#
# SPDX-License-Identifier: MIT

- type: antag
  id: Changeling
  name: roles-antag-changeling-name
  antagonist: true
  setPreference: false # TODO: set this to true once Changeling exits WIP status
  objective: roles-antag-changeling-objective
