// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2026 Ilya Mikheev <me@ilyamikcoder.com>
// SPDX-FileCopyrightText: 2026 Patrik Caes-Sayrs <heartofgoldfish@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Shared.BarSign;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.BarSign.Ui;

[GenerateTypedNameReferences]
public sealed partial class BarSignMenu : FancyWindow
{
    private List<BarSignPrototype> _cachedPrototypes = new();

    public event Action<string>? OnSignSelected;

    public BarSignMenu()
    {
        RobustXamlLoader.Load(this);

        SignOptions.OnItemSelected += idx =>
        {
            OnSignSelected?.Invoke(_cachedPrototypes[idx.Id].ID);
            SignOptions.SelectId(idx.Id);
        };

    }

    public void LoadSigns(List<BarSignPrototype> signs)
    {
        _cachedPrototypes.Clear();
        _cachedPrototypes = signs;

        foreach (var proto in _cachedPrototypes)
        {
            SignOptions.AddItem(Loc.GetString(proto.Name));
        }
    }

    public void UpdateState(BarSignPrototype newSign)
    {
        var idx = _cachedPrototypes.IndexOf(newSign);
        SignOptions.TrySelectId(idx);
    }
}
